insert into user values(1, sysdate(), 'Rajesh Jha');
insert into user values(2, sysdate(), 'Rajpati Jha');
insert into user values(3, sysdate(), 'Ratnesh Jha');
insert into user values(4, sysdate(), 'Rupesh Jha');
insert into posts values(1001, 'my first post', 1);
insert into posts values(1002, 'my second post', 2);
insert into posts values(1003, 'my third post', 3);
insert into posts values(1004, 'my fourth post', 4);
insert into posts values(1005, 'my fourth post', 4);
insert into posts values(1006, 'my fourth post', 4);
insert into posts values(1007, 'my fourth post', 4);
insert into posts values(1008, 'my fourth post', 4);
